### ISSUE TITLE
C2022 - error with VS2022 also

### ISSUE THREAD

**Issue by ejjeamore** [wrljet/hercules-helper-windows#13] opened 2024-11-08 14:35 UTC
Looks like it's in general.c variable tmp says it's going to overwrite 16 bytes. Otherwise script worked like a charm with VS2022 and Win 11!

  Creating library msvc.AMD64.obj\hengine.lib and object msvc.AMD64.obj\hengine.exp
Generating code
C:\Hercules\aethra\general1.c(2269) : error C2220: the following warning is treated as an error
C:\Hercules\aethra\general1.c(2269) : warning C4789: in function 'z900_compare_and_form_codeword' buffer 'tmp' of size 16 bytes will be overrun; 16 bytes will be written starting at offset 16
C:\Hercules\aethra\general1.c(2240) : warning C4789: in function 'z900_compare_and_form_codeword' buffer 'tmp' of size 16 bytes will be overrun; 16 bytes will be written starting at offset 16
LINK : fatal error LNK1257: code generation failed
NMAKE : fatal error U1077: 'link -nologo /RELEASE /LTCG /DEBUG /PDB:msvc.AMD64.pdb

**Comment by ejjeamore** [comment] 2024-11-08 14:38
[hercules-helper-20241107_20-44-53.log](https://github.com/user-attachments/files/17680150/hercules-helper-20241107_20-44-53.log)

**Comment by wrljet** [comment] 2024-11-09 16:06
Hi,

This is a continuing battle with MSVC.  I will create an issue on [Aethra ](https://github.com/Hercules-Aethra/aethra) and work with Jay on it.

Bill

**Comment by ejjeamore** [comment] 2024-11-09 18:32
Sounds goodthxWilliamSent from my iPhoneOn Nov 9, 2024, at 10:07 AM, Bill Lewis ***@***.***> wrote:﻿
Hi,
This is a continuing battle with MSVC.  I will create an issue on Aethra  and work with Jay on it.
Bill

**Comment by wrljet** [comment] 2024-11-10 00:14
I just tried this and "it works for me".  So I'm wondering, did you use the `-GitBranch develop` option with Hercules-Helper?

If not, you're getting ancient code, before the work we've already done to control these warnings.

Bill

**Comment by wrljet** [comment] 2024-11-10 20:54
> I took the "code" zip download off the website 

Hercules-Helper does all the git clone and branch checkout for you.

An example command line would be:

```
.\hercules-buildall.ps1 -VS2022 -BuildDir C:\xfer\aethra -Flavor Aethra -GitBranch develop -ForceClone
```

In this example we're building into `C:\xfer\aethra`, but you can choose any directory you like.

`-Flavor Aethra` tells it to build Hercules-Aethra.  This is the default.
Alternatively you can use `-Flavor=SDL-Hyperion`

By default, it will use the default branch, generally `master` or `main` in most repos.
For SDL-Hyperion and Hercules-Aethra the `master` branch is generally up to date with the latest official release.
These tend to come about once a year.

But we don't want that.  We want newer code which *may* have fixes for our problem.

`-GitBranch develop` tells it to do a `git checkout develop` to get the up-to-date development code.

`-ForceClone` tells it to overwrite anything already in the git clone directory, and would blow away any local changes you made.

Bill

**Comment by ejjeamore** [comment] 2024-11-11 07:16
Thankyou very much for the info, it's appreciated.WilliamSent from my iPhoneOn Nov 10, 2024, at 2:55 PM, Bill Lewis ***@***.***> wrote:﻿

I took the "code" zip download off the website

Hercules-Helper does all the git clone and branch checkout for you.
An example command line would be:
.\hercules-buildall.ps1 -VS2022 -BuildDir C:\xfer\aethra -Flavor Aethra -GitBranch develop -ForceClone

In this example we're building into C:\xfer\aethra, but you can choose any directory you like.
-Flavor Aethra tells it to build Hercules-Aethra.  This is the default.
Alternatively you can use -Flavor=SDL-Hyperion
By default, it will use the default branch, generally master or main in most repos.
For SDL-Hyperion and Hercules-Aethra the master branch is generally up to date with the latest official release.
These tend to come about once a year.
But we don't want that.  We want newer code which may have fixes for our problem.
-GitBranch develop tells it to do a git checkout develop to get the up-to-date development code.
-ForceClone tells it to overwrite anything already in the git clone directory, and would blow away any local changes you made.
Bill

**Comment by wrljet** [comment] 2024-11-11 14:59
Did you try it?

**Comment by ejjeamore** [comment] 2024-11-11 15:50
Not yet but I will and let you know. thxSent from my iPhoneOn Nov 11, 2024, at 8:59 AM, Bill Lewis ***@***.***> wrote:﻿
Did you try it?

**Comment by ejjeamore** [comment] 2024-11-11 16:57
Works PERFECT!!!!! Always nice to have current code.Thanks much for your helpWilliamSent from my iPhoneOn Nov 11, 2024, at 9:49 AM, William Phillips ***@***.***> wrote:﻿Not yet but I will and let you know. thxSent from my iPhoneOn Nov 11, 2024, at 8:59 AM, Bill Lewis ***@***.***> wrote:﻿
Did you try it?

**Comment by wrljet** [comment] 2024-11-13 17:18
Closing as not a bug in Hercules-Helper, and works with `develop` branch of Hercules-Aethra.

**Closed by wrljet** 2024-11-13 17:18 UTC
