### ISSUE TITLE
C2202 erro changed generl.c in aethra folder

### ISSUE THREAD

**Issue by ejjeamore** [wrljet/hercules-helper-windows#14] opened 2024-11-09 16:07 UTC
In arethra directory I changed general1.c line 2145 to:
BYTE    tmp[CFC_MAX_OPSIZE+30];            /* (work field)              */

built all modules retun = 0 and all tests passed. I'm amateur C coder (COBOL , C#) so I'm not sure if it will fix execution.
Don't use -forececlone to rebuild but I used -firewall

My interest is to just see if I can get it working. Interesting project.

**Comment by wrljet** [comment] 2024-11-09 16:09
The problem is actually with modern MSVC giving out incorrect warnings, and having changed that warning to a fatal error.

The Hercules code is OK.

Bill

**Comment by wrljet** [comment] 2024-11-09 16:11
Oh, BTW, these issues should be reported to Aethra, not Hercules-Helper.

**Comment by ejjeamore** [comment] 2024-11-09 16:13
thx

**Comment by wrljet** [comment] 2024-11-09 16:15
Even worse with gcc. It's a continuous battle with the various compilers and their versions.

**Comment by wrljet** [comment] 2024-11-09 16:21
Same as you did here. 

Start with the https://github.com/Hercules-Aethra/aethra/issues repo issues page.

I can do this for you if you'd like.  I'm in reasonably frequent touch with Jay.

**Comment by ejjeamore** [comment] 2024-11-09 16:37
I just found it hercules/arethra, I think,  and added issue but I'm an amateur not knowing the extent of what I changed. Feel free to add commentary since others have this issue

william

**Comment by ejjeamore** [comment] 2024-11-09 18:33
Good to know, I guess they'll get around to fixing that,thxWilliamSent from my iPhoneOn Nov 9, 2024, at 10:15 AM, Bill Lewis ***@***.***> wrote:﻿
Even worse with gcc. It's a continuous battle with the various compilers and their versions.

**Comment by wrljet** [comment] 2024-11-11 23:35
Duplicate of https://github.com/wrljet/hercules-helper-windows/issues/13

**Closed by wrljet** 2024-11-11 23:35 UTC
Labels: duplicate
